GET http://localhost:8080/api/person
Accept: application/json

###
GET http://localhost:8080/api/person/1

###
POST http://localhost:8080/api/person
Content-Type: application/json
Accept: application/json

{
  "name": "Wahyu"
}