// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package person

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Person struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
